/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.view;

import com.example.controller.AppController;


/**
 *
 * @author pierre
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNamePanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        usernameFieldPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordFieldPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        buttonsPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Savings Tracker");
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        appNamePanel.setLayout(new java.awt.BorderLayout());

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNameLabel.setText("Simple Savings Tracker");
        appNameLabel.setToolTipText("");
        appNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appNamePanel.add(appNameLabel, java.awt.BorderLayout.CENTER);

        getContentPane().add(appNamePanel);

        usernameFieldPanel.setPreferredSize(new java.awt.Dimension(642, 124));
        usernameFieldPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username");
        usernameFieldPanel.add(jLabel1);

        usernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTextField.setToolTipText("Input username");
        usernameTextField.setMinimumSize(new java.awt.Dimension(256, 31));
        usernameTextField.setPreferredSize(new java.awt.Dimension(256, 31));
        usernameFieldPanel.add(usernameTextField);

        getContentPane().add(usernameFieldPanel);

        passwordFieldPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        passwordFieldPanel.add(jLabel2);

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordField.setPreferredSize(new java.awt.Dimension(256, 31));
        passwordFieldPanel.add(passwordField);

        getContentPane().add(passwordFieldPanel);

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 24, 5));

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.setToolTipText("");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginButtonMousePressed(evt);
            }
        });
        buttonsPanel.add(loginButton);

        getContentPane().add(buttonsPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMousePressed
        if (evt.getSource() == loginButton) {
            String loginUsername = usernameTextField.getText().trim();
            String loginPassword = new String(passwordField.getPassword()).trim();
            
            if (AppController.loginUser(loginUsername, loginPassword)) {
                this.dispose();
            }
            else {
                
            }
        }
    }//GEN-LAST:event_loginButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel appNamePanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordFieldPanel;
    private javax.swing.JPanel usernameFieldPanel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
